name: Post welcome comment # nome do worflow 
on: #indica quando o workflow será executado
  pull_request: 
    types: [opened] #worflow será executado em pull requests com status opened
permissions: # dá permissões
  pull-requests: write #  workflow pode escrever no repositório
jobs: #cria um trabalho
  build: #contrui um job
    name: Post welcome comment #nome do job
    runs-on: ubuntu-latest #runner (executador) do job
    steps: #etapas do job
      #código shell que comenta automaticamente no commit
      - run: gh pr comment $PR_URL --body "Welcome to the repository!" 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
